### ISSUE TITLE
[Feature]在连接不上IPv6的情况下提示

### ISSUE THREAD

**Issue by cmpute** [cmpute/iTV6#8]
连不上视频资源的话（没有IPv6也不是校内网的话）进行提示。同时还可以加一个显示IPv6地址的功能在About里。

**Comment by AmateurZhang** [comment]
When you issue your UWP to Microsoft Windows Store, the MS test Engineer would let you show your App run on IPV4 Environment. http://ivi.bupt.edu.cn/ can help in this case.
Best Wishes.

**Comment by cmpute** [comment]
@AmateurZhang Thanks for the information! That will help a lot
